-- 회원유형코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'MEM_TYP_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'MEM_TYP_CD', 'A', NULL, NULL, '회원유형코드', '관리자회원', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MEM_TYP_CD', 'E', NULL, NULL, '회원유형코드', '중개회원', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MEM_TYP_CD', 'N', NULL, NULL, '회원유형코드', '일반회원', NULL, 3.00, NOW(), 'N' );

-- SNS구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'SNS_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'SNS_GB_CD', 'N', NULL, NULL, 'SNS구분코드', '네이버', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SNS_GB_CD', 'K', NULL, NULL, 'SNS구분코드', '카카오', NULL, 2.00, NOW(), 'N' );

-- 약관버전
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'TERMS_VER' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'TERMS_VER', 'AGE_14_OVR_AGRE', NULL, NULL, '약관버전', '[필수]만14세이상동의', '20230904_01', 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TERMS_VER', 'SVC_USE_AGRE', NULL, NULL, '약관버전', '[필수]서비스이용동의', '20230904_01', 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TERMS_VER', 'PRSNL_INF_AGRE', NULL, NULL, '약관버전', '[필수]개인정보수집및이용동의', '20230904_01', 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TERMS_VER', 'MKT_RCV_AGRE', NULL, NULL, '약관버전', '[선택]마케팅정보수신동의', '20230904_01', 4.00, NOW(), 'N' );

-- 과세유형구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'TAXATION_TYP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'TAXATION_TYP_GB_CD', '01', NULL, NULL, '과세유형구분코드', '부가가치세 일반과세자', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TAXATION_TYP_GB_CD', '02', NULL, NULL, '과세유형구분코드', '부가가치세 간이과세자', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TAXATION_TYP_GB_CD', '03', NULL, NULL, '과세유형구분코드', '부가가치세 과세특례자', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TAXATION_TYP_GB_CD', '04', NULL, NULL, '과세유형구분코드', '부가가치세 면세사업자', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TAXATION_TYP_GB_CD', '05', NULL, NULL, '과세유형구분코드', '수익사업을 영위하지 않는 비영리법인이거나 고유번호가 부여된 단체,국가기관 등', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TAXATION_TYP_GB_CD', '06', NULL, NULL, '과세유형구분코드', '고유번호가 부여된 단체', NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TAXATION_TYP_GB_CD', '07', NULL, NULL, '과세유형구분코드', '부가가치세 간이과세자(세금계산서 발급사업자)', NULL, 7.00, NOW(), 'N' );

-- 사업자상태구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'BIZ_STATE_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'BIZ_STATE_GB_CD', '01', NULL, NULL, '사업자상태구분코드', '계속사업자', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BIZ_STATE_GB_CD', '02', NULL, NULL, '사업자상태구분코드', '휴업자', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BIZ_STATE_GB_CD', '03', NULL, NULL, '사업자상태구분코드', '폐업자', NULL, 3.00, NOW(), 'N' );

-- 첨부파일구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'ATTCH_FILE_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'ATTCH_FILE_GB_CD', 'BIZ_REG_IMG', NULL, NULL, '첨부파일구분코드', '사업자등록증 이미지파일', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ATTCH_FILE_GB_CD', 'EST_REG_IMG', NULL, NULL, '첨부파일구분코드', '중개등록증 이미지파일', NULL, 1.10, NOW(), 'N' );

-- 알림톡메시지템플릿코드
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'MSG_TMPLT_CD';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'MSG_TMPLT_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'MSG_TMPLT_CD', 'TMPLT_001', NULL, NULL, '알림톡메시지템플릿코드', '휴대폰본인인증 인증번호 전송', 'TMPLT_001_SEFZpdRYE', 1.10, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MSG_TMPLT_CD', 'TMPLT_002', NULL, NULL, '알림톡메시지템플릿코드', '중개회원 가입승인 안내', 'TMPLT_002_nP1yx5wjM', 1.20, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MSG_TMPLT_CD', 'TMPLT_003', NULL, NULL, '알림톡메시지템플릿코드', '중개회원 가입거부 안내', 'TMPLT_003_kaSqTJjjM', 1.30, NOW(), 'N' );

-- 알림톡메시지대체발송상태코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'RESEND_STAT_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'RESEND_STAT_CD', 'RSC01', NULL, NULL, '알림톡메시지대체발송상태코드', '대체 발송 미대상', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'RESEND_STAT_CD', 'RSC02', NULL, NULL, '알림톡메시지대체발송상태코드', '대체 발송 대상', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'RESEND_STAT_CD', 'RSC03', NULL, NULL, '알림톡메시지대체발송상태코드', '대체 발송 중', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'RESEND_STAT_CD', 'RSC04', NULL, NULL, '알림톡메시지대체발송상태코드', '대체 발송 성공', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'RESEND_STAT_CD', 'RSC05', NULL, NULL, '알림톡메시지대체발송상태코드', '대체 발송 실패', NULL, 1.00, NOW(), 'N' );

-- 로그인이력구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'LOGIN_HIST_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'LOGIN_HIST_GB_CD', 'EMAIL_S', NULL, NULL, '로그인이력구분코드', '이메일로 로그인', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LOGIN_HIST_GB_CD', 'EMAIL_A', NULL, NULL, '로그인이력구분코드', '이메일로 자동 로그인', NULL, 1.10, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LOGIN_HIST_GB_CD', 'EMAIL_F', NULL, NULL, '로그인이력구분코드', '이메일로 로그인 실패', NULL, 1.90, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LOGIN_HIST_GB_CD', 'SNS', NULL, NULL, '로그인이력구분코드', 'SNS 로그인', NULL, 2.00, NOW(), 'N' );

-- 매물유형구분코드
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'ESTATE_TYP_GB_CD';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'ESTATE_TYP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_GB_CD', 'REGIDENTAL', NULL, NULL, '매물유형구분코드', '주거용', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_GB_CD', 'COMMERCIAL', NULL, NULL, '매물유형구분코드', '상업용', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_GB_CD', 'PRESALE', NULL, NULL, '매물유형구분코드', '분양권', NULL, 3.00, NOW(), 'N' );

-- 매물구분코드 - 주거용
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'ESTATE_TYP_CD' AND UP_COMN_CD = 'ESTATE_TYP_GB_CD' AND UP_ITEM_CD = 'REGIDENTAL';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'ESTATE_TYP_CD' AND UP_COMN_CD = 'ESTATE_TYP_GB_CD' AND UP_ITEM_CD = 'REGIDENTAL' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'APT', 'ESTATE_TYP_GB_CD', 'REGIDENTAL', '매물구분코드', '아파트', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'OFT', 'ESTATE_TYP_GB_CD', 'REGIDENTAL', '매물구분코드', '오피스텔', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'SMH', 'ESTATE_TYP_GB_CD', 'REGIDENTAL', '매물구분코드', '단독/다가구', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'TWN', 'ESTATE_TYP_GB_CD', 'REGIDENTAL', '매물구분코드', '다세대/빌라/연립', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'SHC', 'ESTATE_TYP_GB_CD', 'REGIDENTAL', '매물구분코드', '상가주택', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'HUS', 'ESTATE_TYP_GB_CD', 'REGIDENTAL', '매물구분코드', '주택', NULL, 6.00, NOW(), 'N' );

-- 매물구분코드 - 상업용
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'ESTATE_TYP_CD' AND UP_COMN_CD = 'ESTATE_TYP_GB_CD' AND UP_ITEM_CD = 'COMMERCIAL';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'ESTATE_TYP_CD' AND UP_COMN_CD = 'ESTATE_TYP_GB_CD' AND UP_ITEM_CD = 'COMMERCIAL' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'KOG', 'ESTATE_TYP_GB_CD', 'COMMERCIAL', '매물구분코드', '지산/사무실/창고', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'STR', 'ESTATE_TYP_GB_CD', 'COMMERCIAL', '매물구분코드', '상가', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'BLD', 'ESTATE_TYP_GB_CD', 'COMMERCIAL', '매물구분코드', '건물', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'LND', 'ESTATE_TYP_GB_CD', 'COMMERCIAL', '매물구분코드', '토지/임야', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'FTR', 'ESTATE_TYP_GB_CD', 'COMMERCIAL', '매물구분코드', '단독공장', NULL, 5.00, NOW(), 'N' );

-- 매물구분코드 - 분양권
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'ESTATE_TYP_CD' AND UP_COMN_CD = 'ESTATE_TYP_GB_CD' AND UP_ITEM_CD = 'PRESALE';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'ESTATE_TYP_CD' AND UP_COMN_CD = 'ESTATE_TYP_GB_CD' AND UP_ITEM_CD = 'PRESALE' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'CPS', 'ESTATE_TYP_GB_CD', 'PRESALE', '매물구분코드', '지식산업센터분양권', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'SPS', 'ESTATE_TYP_GB_CD', 'PRESALE', '매물구분코드', '상가분양권', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'APS', 'ESTATE_TYP_GB_CD', 'PRESALE', '매물구분코드', '아파트분양권', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ESTATE_TYP_CD', 'OPS', 'ESTATE_TYP_GB_CD', 'PRESALE', '매물구분코드', '오피스텔분양권', NULL, 4.00, NOW(), 'N' );



-- 거래유형구분코드-전체
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'TRAN_TYP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_GB_CD', 'TRADE', NULL, NULL, '거래유형구분코드', '매매', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_GB_CD', 'LEASE', NULL, NULL, '거래유형구분코드', '임대', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_GB_CD', 'LEASE_ST', NULL, NULL, '거래유형구분코드', '단기임대', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_GB_CD', 'CHARTER', NULL, NULL, '거래유형구분코드', '전세', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_GB_CD', 'MONTLY', NULL, NULL, '거래유형구분코드', '월세', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_GB_CD', 'RESALE', NULL, NULL, '거래유형구분코드', '전매', NULL, 6.00, NOW(), 'N' );

-- 거래유형구분코드-상업용
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'TRAN_TYP_COMRS_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_COMRS_GB_CD', 'TRADE', NULL, NULL, '거래유형구분코드-상업용', '매매', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_COMRS_GB_CD', 'LEASE', NULL, NULL, '거래유형구분코드-상업용', '임대', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_COMRS_GB_CD', 'LEASE_ST', NULL, NULL, '거래유형구분코드-상업용', '단기임대', NULL, 3.00, NOW(), 'N' );

-- 거래유형구분코드-주거용
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'TRAN_TYP_LIVE_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_LIVE_GB_CD', 'TRADE', NULL, NULL, '거래유형구분코드-주거용', '매매', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_LIVE_GB_CD', 'CHARTER', NULL, NULL, '거래유형구분코드-주거용', '전세', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_LIVE_GB_CD', 'MONTLY', NULL, NULL, '거래유형구분코드-주거용', '월세', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_LIVE_GB_CD', 'LEASE_ST', NULL, NULL, '거래유형구분코드-주거용', '단기임대', NULL, 4.00, NOW(), 'N' );

-- 거래유형구분코드-분양권
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'TRAN_TYP_PRESALE_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_PRESALE_GB_CD', 'RESALE', NULL, NULL, '거래유형구분코드-분양권', '전매', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'TRAN_TYP_PRESALE_GB_CD', 'MONTLY', NULL, NULL, '거래유형구분코드-분양권', '월세', NULL, 2.00, NOW(), 'N' );


-- 입주가능일유형코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'PSBL_MOV_DAY_TYP_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'PSBL_MOV_DAY_TYP_CD', 'IMMDTLY', NULL, NULL, '거래유형구분코드', '즉시입주', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'PSBL_MOV_DAY_TYP_CD', 'DISCSN', NULL, NULL, '거래유형구분코드', '날짜협의', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'PSBL_MOV_DAY_TYP_CD', 'INPUT', NULL, NULL, '거래유형구분코드', '직접입력', NULL, 3.00, NOW(), 'N' );

-- 관리비유형코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'MNTNCE_COST_TYP_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'MNTNCE_COST_TYP_CD', 'CLN', NULL, NULL, '관리비유형코드', '청소비', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MNTNCE_COST_TYP_CD', 'GRD', NULL, NULL, '관리비유형코드', '경비비', NULL, 1.10, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MNTNCE_COST_TYP_CD', 'NET', NULL, NULL, '관리비유형코드', '인터넷', NULL, 1.20, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MNTNCE_COST_TYP_CD', 'ELV', NULL, NULL, '관리비유형코드', '승강기유지비', NULL, 1.30, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MNTNCE_COST_TYP_CD', 'FIX', NULL, NULL, '관리비유형코드', '수선유지비', NULL, 1.40, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MNTNCE_COST_TYP_CD', 'ELT', NULL, NULL, '관리비유형코드', '전기세', NULL, 1.50, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MNTNCE_COST_TYP_CD', 'WTR', NULL, NULL, '관리비유형코드', '수도세', NULL, 1.60, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MNTNCE_COST_TYP_CD', 'GAS', NULL, NULL, '관리비유형코드', '도시가스비', NULL, 1.70, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MNTNCE_COST_TYP_CD', 'ETC', NULL, NULL, '관리비유형코드', '기타', NULL, 9.90, NOW(), 'N' );

-- 융자금구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'LOAN_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'LOAN_GB_CD', 'NOT', NULL, NULL, '융자금구분코드', '없음', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LOAN_GB_CD', 'U30', NULL, NULL, '융자금구분코드', '30% 미만', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LOAN_GB_CD', 'O30', NULL, NULL, '융자금구분코드', '30% 이상', NULL, 3.00, NOW(), 'N' );

-- 내부구조유형코드
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'INTNL_STRCTR_TYP_CD';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'INTNL_STRCTR_TYP_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'INTNL_STRCTR_TYP_CD', 'MULTI', NULL, NULL, '내부구조유형코드', '복층', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'INTNL_STRCTR_TYP_CD', 'SEPAR', NULL, NULL, '내부구조유형코드', '1.5룸/주방분리형', NULL, 2.00, NOW(), 'N' );

-- 옵션항목유형구분코드
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_GB_CD'
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_GB_CD', 'FACLT', 	NULL, NULL, '옵션항목유형구분코드', '시설(전체)', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_GB_CD', 'FACLT_CMMRC', NULL, NULL, '옵션항목유형구분코드', '시설-상업용', NULL, 1.10, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_GB_CD', 'FACLT_STORE', NULL, NULL, '옵션항목유형구분코드', '시설-상가용', NULL, 1.20, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_GB_CD', 'KTCHN', NULL, NULL, '옵션항목유형구분코드', '주방', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_GB_CD', 'ELCTR', NULL, NULL, '옵션항목유형구분코드', '가전', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_GB_CD', 'FNCHR', NULL, NULL, '옵션항목유형구분코드', '가구', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_GB_CD', 'SCRTY', NULL, NULL, '옵션항목유형구분코드', '보안(전체)', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_CMMRC', NULL, NULL, '옵션항목유형구분코드', '보안-상업용', NULL, 5.10, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_STORE', NULL, NULL, '옵션항목유형구분코드', '보안-상가용', NULL, 5.20, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_LIVE', NULL, NULL, '옵션항목유형구분코드', '보안-주거용', NULL, 5.30, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_GB_CD', 'ETC', NULL, NULL, '옵션항목유형구분코드', '기타', NULL, 6.00, NOW(), 'N' );


-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD' ORDER BY SORT_SERL;

-- 옵션항목구분코드 - 시설(전체)
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD' AND UP_COMN_CD = 'OPTION_ITEM_TYP_GB_CD' AND UP_ITEM_CD = 'FACLT' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'VRDR', 'OPTION_ITEM_TYP_GB_CD', 'FACLT', '옵션항목구분코드', '베란다', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'TRRC', 'OPTION_ITEM_TYP_GB_CD', 'FACLT', '옵션항목구분코드', '테라스', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'GRGE', 'OPTION_ITEM_TYP_GB_CD', 'FACLT', '옵션항목구분코드', '창고', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'WTSP', 'OPTION_ITEM_TYP_GB_CD', 'FACLT', '옵션항목구분코드', '급수시설', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'EXHT', 'OPTION_ITEM_TYP_GB_CD', 'FACLT', '옵션항목구분코드', '급배기시설', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'VNTL', 'OPTION_ITEM_TYP_GB_CD', 'FACLT', '옵션항목구분코드', '환기시설', NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'REST', 'OPTION_ITEM_TYP_GB_CD', 'FACLT', '옵션항목구분코드', '휴게공간', NULL, 7.00, NOW(), 'N' );

-- 옵션항목구분코드 - 시설-상업용
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD' AND UP_COMN_CD = 'OPTION_ITEM_TYP_GB_CD' AND UP_ITEM_CD = 'FACLT_CMMRC' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'VRDR', 'OPTION_ITEM_TYP_GB_CD', 'FACLT_CMMRC', '옵션항목구분코드', '베란다', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'TRRC', 'OPTION_ITEM_TYP_GB_CD', 'FACLT_CMMRC', '옵션항목구분코드', '테라스', NULL, 2.00, NOW(), 'N' );

-- 옵션항목구분코드 - 시설-상가용
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD' AND UP_COMN_CD = 'OPTION_ITEM_TYP_GB_CD' AND UP_ITEM_CD = 'FACLT_STORE' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'GRGE', 'OPTION_ITEM_TYP_GB_CD', 'FACLT_STORE', '옵션항목구분코드', '창고', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'WTSP', 'OPTION_ITEM_TYP_GB_CD', 'FACLT_STORE', '옵션항목구분코드', '급수시설', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'EXHT', 'OPTION_ITEM_TYP_GB_CD', 'FACLT_STORE', '옵션항목구분코드', '급배기시설', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'VNTL', 'OPTION_ITEM_TYP_GB_CD', 'FACLT_STORE', '옵션항목구분코드', '환기시설', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'REST', 'OPTION_ITEM_TYP_GB_CD', 'FACLT_STORE', '옵션항목구분코드', '휴게공간', NULL, 5.00, NOW(), 'N' );

-- 옵션항목구분코드 - 주방
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD' AND UP_COMN_CD = 'OPTION_ITEM_TYP_GB_CD' AND UP_ITEM_CD = 'KTCHN' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'INDN', 'OPTION_ITEM_TYP_GB_CD', 'KTCHN', '옵션항목구분코드', '인덕션', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'GSRG', 'OPTION_ITEM_TYP_GB_CD', 'KTCHN', '옵션항목구분코드', '가스레인지', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'ETRG', 'OPTION_ITEM_TYP_GB_CD', 'KTCHN', '옵션항목구분코드', '전자레인지', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'OVEN', 'OPTION_ITEM_TYP_GB_CD', 'KTCHN', '옵션항목구분코드', '오븐', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'DSCL', 'OPTION_ITEM_TYP_GB_CD', 'KTCHN', '옵션항목구분코드', '식기세척기', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'SYNC', 'OPTION_ITEM_TYP_GB_CD', 'KTCHN', '옵션항목구분코드', '싱크대', NULL, 6.00, NOW(), 'N' );

-- 옵션항목구분코드 - 가전
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD' AND UP_COMN_CD = 'OPTION_ITEM_TYP_GB_CD' AND UP_ITEM_CD = 'ELCTR' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'WRNT', 'OPTION_ITEM_TYP_GB_CD', 'ELCTR', '옵션항목구분코드', '무선인터넷', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'ACDN', 'OPTION_ITEM_TYP_GB_CD', 'ELCTR', '옵션항목구분코드', '에어컨', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'WMCN', 'OPTION_ITEM_TYP_GB_CD', 'ELCTR', '옵션항목구분코드', '세탁기', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'RFRT', 'OPTION_ITEM_TYP_GB_CD', 'ELCTR', '옵션항목구분코드', '냉장고', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'BDET', 'OPTION_ITEM_TYP_GB_CD', 'ELCTR', '옵션항목구분코드', '비데', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'TLVS', 'OPTION_ITEM_TYP_GB_CD', 'ELCTR', '옵션항목구분코드', 'TV', NULL, 6.00, NOW(), 'N' );

-- 옵션항목구분코드 - 가구
-- DELETE FROM TB_COMN_CD WHERE UP_COMN_CD = 'OPTION_ITEM_TYP_GB_CD' AND UP_ITEM_CD = 'FNCHR' AND ITEM_CD = 'TLVS';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD' AND UP_COMN_CD = 'OPTION_ITEM_TYP_GB_CD' AND UP_ITEM_CD = 'FNCHR' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'BTCF', 'OPTION_ITEM_TYP_GB_CD', 'FNCHR', '옵션항목구분코드', '붙박이장', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'DRSR', 'OPTION_ITEM_TYP_GB_CD', 'FNCHR', '옵션항목구분코드', '드레스룸', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'SHSR', 'OPTION_ITEM_TYP_GB_CD', 'FNCHR', '옵션항목구분코드', '신발장', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'BATH', 'OPTION_ITEM_TYP_GB_CD', 'FNCHR', '옵션항목구분코드', '욕조', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'KTBL', 'OPTION_ITEM_TYP_GB_CD', 'FNCHR', '옵션항목구분코드', '식탁', NULL, 5.00, NOW(), 'N' );

-- 옵션항목구분코드 - 보안(전체)
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD' AND UP_COMN_CD = 'OPTION_ITEM_TYP_GB_CD' AND UP_ITEM_CD = 'SCRTY' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'CCTV', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY', '옵션항목구분코드', 'CCTV', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'NMPC', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY', '옵션항목구분코드', '무인택배함', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'GDWD', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY', '옵션항목구분코드', '방범창', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'SCRT', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY', '옵션항목구분코드', '자체경비원', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'SCMW', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY', '옵션항목구분코드', '관리인상주', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'DDOR', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY', '옵션항목구분코드', '디지털도어락', NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'VDPH', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY', '옵션항목구분코드', '비디오폰', NULL, 7.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'CRDK', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY', '옵션항목구분코드', '카드키', NULL, 8.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'ATFR', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY', '옵션항목구분코드', '소화기', NULL, 9.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'FRSC', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY', '옵션항목구분코드', '화재감지기', NULL, 10.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'FALM', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY', '옵션항목구분코드', '화재경보기', NULL, 11.00, NOW(), 'N' );

-- 옵션항목구분코드 - 보안-상업용
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD' AND UP_COMN_CD = 'OPTION_ITEM_TYP_GB_CD' AND UP_ITEM_CD = 'SCRTY_CMMRC' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'CCTV', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_CMMRC', '옵션항목구분코드', 'CCTV', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'SCRT', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_CMMRC', '옵션항목구분코드', '자체경비원', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'DDOR', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_CMMRC', '옵션항목구분코드', '디지털도어락', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'ATFR', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_CMMRC', '옵션항목구분코드', '소화기', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'FRSC', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_CMMRC', '옵션항목구분코드', '화재감지기', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'FALM', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_CMMRC', '옵션항목구분코드', '화재경보기', NULL, 6.00, NOW(), 'N' );

-- 옵션항목구분코드 - 보안-상가용
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD' AND UP_COMN_CD = 'OPTION_ITEM_TYP_GB_CD' AND UP_ITEM_CD = 'SCRTY_STORE' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'CCTV', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_STORE', '옵션항목구분코드', 'CCTV', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'SCMW', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_STORE', '옵션항목구분코드', '관리인상주', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'ATFR', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_STORE', '옵션항목구분코드', '소화기', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'FRSC', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_STORE', '옵션항목구분코드', '화재감지기', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'FALM', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_STORE', '옵션항목구분코드', '화재경보기', NULL, 5.00, NOW(), 'N' );

-- 옵션항목구분코드 - 보안-주거용
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD' AND UP_COMN_CD = 'OPTION_ITEM_TYP_GB_CD' AND UP_ITEM_CD = 'SCRTY_LIVE' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'DDOR', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_LIVE', '옵션항목구분코드', '디지털도어락', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'CRDK', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_LIVE', '옵션항목구분코드', '카드키', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'NMPC', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_LIVE', '옵션항목구분코드', '무인택배함', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'GDWD', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_LIVE', '옵션항목구분코드', '방범창', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'SCRT', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_LIVE', '옵션항목구분코드', '자체경비원', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'VDPH', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_LIVE', '옵션항목구분코드', '비디오폰', NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'FALM', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_LIVE', '옵션항목구분코드', '화재경보기', NULL, 7.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'CCTV', 'OPTION_ITEM_TYP_GB_CD', 'SCRTY_LIVE', '옵션항목구분코드', 'CCTV', NULL, 8.00, NOW(), 'N' );

-- 옵션항목구분코드 - 기타
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'OPTION_ITEM_TYP_CD' AND UP_COMN_CD = 'OPTION_ITEM_TYP_GB_CD' AND UP_ITEM_CD = 'ETC' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'VRDR', 'OPTION_ITEM_TYP_GB_CD', 'ETC', '옵션항목구분코드', '베란다', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'TRRC', 'OPTION_ITEM_TYP_GB_CD', 'ETC', '옵션항목구분코드', '테라스', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'BLCN', 'OPTION_ITEM_TYP_GB_CD', 'ETC', '옵션항목구분코드', '발코니', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'OPTION_ITEM_TYP_CD', 'YARD', 'OPTION_ITEM_TYP_GB_CD', 'ETC', '옵션항목구분코드', '마당', NULL, 4.00, NOW(), 'N' );

-- 층별용도구분코드
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'FL_USAGE_GB_CD';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'FLR_USAGE_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'FLR_USAGE_GB_CD', '10', NULL, NULL, '층별용도구분코드', '근생지원시설', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'FLR_USAGE_GB_CD', '20', NULL, NULL, '층별용도구분코드', '지식산업센터(공장)', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'FLR_USAGE_GB_CD', '30', NULL, NULL, '층별용도구분코드', '공동창고', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'FLR_USAGE_GB_CD', '40', NULL, NULL, '층별용도구분코드', '기숙사,어린이집', NULL, 4.00, NOW(), 'N' );

-- 건축물용도구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'BLD_USAGE_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '010', NULL, NULL, '건축물용도구분코드', '단독주택', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '020', NULL, NULL, '건축물용도구분코드', '공동주택', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '030', NULL, NULL, '건축물용도구분코드', '업무시설', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '040', NULL, NULL, '건축물용도구분코드', '근린생활시설', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '050', NULL, NULL, '건축물용도구분코드', '의료시설', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '060', NULL, NULL, '건축물용도구분코드', '교육연구시설', NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '070', NULL, NULL, '건축물용도구분코드', '판매시설', NULL, 7.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '080', NULL, NULL, '건축물용도구분코드', '운동시설', NULL, 8.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '090', NULL, NULL, '건축물용도구분코드', '숙박시설', NULL, 9.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '100', NULL, NULL, '건축물용도구분코드', '문화및집회시설', NULL, 10.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '110', NULL, NULL, '건축물용도구분코드', '위락시설', NULL, 11.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '120', NULL, NULL, '건축물용도구분코드', '창고시설', NULL, 12.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '130', NULL, NULL, '건축물용도구분코드', '공장', NULL, 13.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '980', NULL, NULL, '건축물용도구분코드', '기타', NULL, 98.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_USAGE_GB_CD', '990', NULL, NULL, '건축물용도구분코드', '구분없음', NULL, 99.00, NOW(), 'N' );

-- 건물방향구분코드
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'BLK_DIRCTN_GB_CD';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'BLD_DIRCTN_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'BLD_DIRCTN_GB_CD', 'E', NULL, NULL, '건물방향구분코드', '동', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_DIRCTN_GB_CD', 'W', NULL, NULL, '건물방향구분코드', '서', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_DIRCTN_GB_CD', 'S', NULL, NULL, '건물방향구분코드', '남', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_DIRCTN_GB_CD', 'N', NULL, NULL, '건물방향구분코드', '북', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_DIRCTN_GB_CD', 'NE', NULL, NULL, '건물방향구분코드', '북동', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_DIRCTN_GB_CD', 'SE', NULL, NULL, '건물방향구분코드', '남동', NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_DIRCTN_GB_CD', 'NW', NULL, NULL, '건물방향구분코드', '북서', NULL, 7.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BLD_DIRCTN_GB_CD', 'SW', NULL, NULL, '건물방향구분코드', '남서', NULL, 8.00, NOW(), 'N' );

-- 난방종류구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'HEAT_KIND_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'HEAT_KIND_GB_CD', 'PRVT', NULL, NULL, '난방종류구분코드', '개별난방', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'HEAT_KIND_GB_CD', 'CNTR', NULL, NULL, '난방종류구분코드', '중앙난방', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'HEAT_KIND_GB_CD', 'AREA', NULL, NULL, '난방종류구분코드', '지역난방', NULL, 3.00, NOW(), 'N' );

-- 층고유형구분코드
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'FLR_HGHT_TYP_GB_CD';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'FLR_HGHT_TYP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'FLR_HGHT_TYP_GB_CD', '01', NULL, NULL, '층고유형구분코드', '3.5M 이하', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'FLR_HGHT_TYP_GB_CD', '02', NULL, NULL, '층고유형구분코드', '3.6~4.5M', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'FLR_HGHT_TYP_GB_CD', '03', NULL, NULL, '층고유형구분코드', '4.6~5.5M', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'FLR_HGHT_TYP_GB_CD', '04', NULL, NULL, '층고유형구분코드', '5.6~6.5M', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'FLR_HGHT_TYP_GB_CD', '05', NULL, NULL, '층고유형구분코드', '6.6M 이상', NULL, 5.00, NOW(), 'N' );

-- 사용전력유형구분코드
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'ELCTR_PWR_TYP_GB_CD';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'ELCTR_PWR_TYP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'ELCTR_PWR_TYP_GB_CD', '01', NULL, NULL, '사용전력유형구분코드', '10KW 이하', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ELCTR_PWR_TYP_GB_CD', '02', NULL, NULL, '사용전력유형구분코드', '11~25KW', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ELCTR_PWR_TYP_GB_CD', '03', NULL, NULL, '사용전력유형구분코드', '26~50KW', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ELCTR_PWR_TYP_GB_CD', '04', NULL, NULL, '사용전력유형구분코드', '51~100KW', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ELCTR_PWR_TYP_GB_CD', '05', NULL, NULL, '사용전력유형구분코드', '101~1,000KW', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ELCTR_PWR_TYP_GB_CD', '06', NULL, NULL, '사용전력유형구분코드', '1,000KW 초과', NULL, 6.00, NOW(), 'N' );

-- 지식산업센터첨부이미지유형구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'KNWLDG_CMPLX_ATCH_IMG_TYP_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'KNWLDG_CMPLX_ATCH_IMG_TYP_CD', 'VWMAP', NULL, NULL, '지식산업센터첨부이미지유형구분코드', '조감도', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'KNWLDG_CMPLX_ATCH_IMG_TYP_CD', 'FEATR', NULL, NULL, '지식산업센터첨부이미지유형구분코드', '특장점', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'KNWLDG_CMPLX_ATCH_IMG_TYP_CD', 'FRMAP', NULL, NULL, '지식산업센터첨부이미지유형구분코드', '층별도면', NULL, 3.00, NOW(), 'N' );

-- 사용승인년도검색항목코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'USE_CNFRM_YEAR_SRCH_TYP_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'USE_CNFRM_YEAR_SRCH_TYP_CD', 'ALL', NULL, NULL, '사용승인년도검색항목코드', '전체', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'USE_CNFRM_YEAR_SRCH_TYP_CD', 'IN_1Y', NULL, NULL, '사용승인년도검색항목코드', '1년이내', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'USE_CNFRM_YEAR_SRCH_TYP_CD', 'IN_2Y', NULL, NULL, '사용승인년도검색항목코드', '2년이내', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'USE_CNFRM_YEAR_SRCH_TYP_CD', 'IN_5Y', NULL, NULL, '사용승인년도검색항목코드', '5년이내', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'USE_CNFRM_YEAR_SRCH_TYP_CD', 'IN_10Y', NULL, NULL, '사용승인년도검색항목코드', '10년이내', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'USE_CNFRM_YEAR_SRCH_TYP_CD', 'IN_15Y', NULL, NULL, '사용승인년도검색항목코드', '15년이내', NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'USE_CNFRM_YEAR_SRCH_TYP_CD', 'OV_15Y', NULL, NULL, '사용승인년도검색항목코드', '15년이상', NULL, 7.00, NOW(), 'N' );

-- 업종구분코드
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'SECTR_GB_CD';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'SECTR_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'SECTR_GB_CD', '01', NULL, NULL, '업종구분코드', '휴게음식점', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SECTR_GB_CD', '02', NULL, NULL, '업종구분코드', '일반음식점', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SECTR_GB_CD', '03', NULL, NULL, '업종구분코드', '주류점', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SECTR_GB_CD', '04', NULL, NULL, '업종구분코드', '오락스포츠', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SECTR_GB_CD', '05', NULL, NULL, '업종구분코드', '판매업', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SECTR_GB_CD', '06', NULL, NULL, '업종구분코드', '서비스업', NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SECTR_GB_CD', '07', NULL, NULL, '업종구분코드', '숙박업', NULL, 7.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SECTR_GB_CD', '99', NULL, NULL, '업종구분코드', '기타업종', NULL, 99.00, NOW(), 'N' );

-- 토지임야현재용도구분코드
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'LND_CRNT_USAGE_GB_CD';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'LND_CRNT_USAGE_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '01', NULL, NULL, '토지임야현재용도구분코드', '전', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '02', NULL, NULL, '토지임야현재용도구분코드', '답', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '03', NULL, NULL, '토지임야현재용도구분코드', '과수원', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '04', NULL, NULL, '토지임야현재용도구분코드', '임야', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '05', NULL, NULL, '토지임야현재용도구분코드', '광천지', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '06', NULL, NULL, '토지임야현재용도구분코드', '염전', NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '07', NULL, NULL, '토지임야현재용도구분코드', '대지', NULL, 7.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '08', NULL, NULL, '토지임야현재용도구분코드', '공장용지', NULL, 8.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '09', NULL, NULL, '토지임야현재용도구분코드', '학교용지', NULL, 9.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '10', NULL, NULL, '토지임야현재용도구분코드', '주차장', NULL, 10.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '11', NULL, NULL, '토지임야현재용도구분코드', '주유소용지', NULL, 11.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '12', NULL, NULL, '토지임야현재용도구분코드', '창고용지', NULL, 12.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '13', NULL, NULL, '토지임야현재용도구분코드', '도로', NULL, 13.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '14', NULL, NULL, '토지임야현재용도구분코드', '철도용지', NULL, 14.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '15', NULL, NULL, '토지임야현재용도구분코드', '제방', NULL, 15.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '16', NULL, NULL, '토지임야현재용도구분코드', '하천', NULL, 16.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '17', NULL, NULL, '토지임야현재용도구분코드', '구거', NULL, 17.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '18', NULL, NULL, '토지임야현재용도구분코드', '유지', NULL, 18.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '19', NULL, NULL, '토지임야현재용도구분코드', '양어장', NULL, 19.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '20', NULL, NULL, '토지임야현재용도구분코드', '수도용지', NULL, 20.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '21', NULL, NULL, '토지임야현재용도구분코드', '공원', NULL, 21.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '22', NULL, NULL, '토지임야현재용도구분코드', '체육용지', NULL, 22.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '23', NULL, NULL, '토지임야현재용도구분코드', '유원지', NULL, 23.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '24', NULL, NULL, '토지임야현재용도구분코드', '종교용지', NULL, 24.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '25', NULL, NULL, '토지임야현재용도구분코드', '사적지', NULL, 25.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '26', NULL, NULL, '토지임야현재용도구분코드', '묘지', NULL, 26.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LND_CRNT_USAGE_GB_CD', '27', NULL, NULL, '토지임야현재용도구분코드', '잡종지', NULL, 27.00, NOW(), 'N' );

-- 실시간분양현장지역필터코드
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'KNWLDG_AREA_FILTER_CD'
-- SUGGSTN_SALES_REGION_GB_CD
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'SUGGSTN_SALES_REGION_GB_CD' ORDER BY SORT_SERL;

INSERT INTO TB_COMN_CD VALUES ( 'KNWLDG_AREA_FILTER_CD', '', NULL, NULL, '실시간분양현장지역필터코드', '전체', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '001', NULL, NULL, '실시간분양현장지역필터코드', '서울', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '002', NULL, NULL, '실시간분양현장지역필터코드', '성수동', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '003', NULL, NULL, '실시간분양현장지역필터코드', '문정동', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '004', NULL, NULL, '실시간분양현장지역필터코드', '영등포', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '005', NULL, NULL, '실시간분양현장지역필터코드', '가산/구로', NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '101', NULL, NULL, '실시간분양현장지역필터코드', '인천/부천', NULL, 7.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '102', NULL, NULL, '실시간분양현장지역필터코드', '시흥/안산', NULL, 8.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '103', NULL, NULL, '실시간분양현장지역필터코드', '과천/광명', NULL, 9.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '104', NULL, NULL, '실시간분양현장지역필터코드', '안양/군포', NULL, 10.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '105', NULL, NULL, '실시간분양현장지역필터코드', '수원/의왕', NULL, 11.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '106', NULL, NULL, '실시간분양현장지역필터코드', '하남/성남', NULL, 12.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '107', NULL, NULL, '실시간분양현장지역필터코드', '김포/고양', NULL, 13.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '108', NULL, NULL, '실시간분양현장지역필터코드', '구리/남양주', NULL, 14.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '109', NULL, NULL, '실시간분양현장지역필터코드', '동탄/용인', NULL, 15.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '110', NULL, NULL, '실시간분양현장지역필터코드', '오산/평택', NULL, 16.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '111', NULL, NULL, '실시간분양현장지역필터코드', '부산', NULL, 17.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGSTN_SALES_REGION_GB_CD', '999', NULL, NULL, '실시간분양현장지역필터코드', '기타', NULL, 18.00, NOW(), 'N' );

-- 분양상태구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'PO_STAT_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'PO_STAT_GB_CD', 'E', NULL, NULL, '분양상태구분코드', '분양예정', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'PO_STAT_GB_CD', 'I', NULL, NULL, '분양상태구분코드', '분양중', NULL, 2.00, NOW(), 'N' );

-- 등록종류코드
-- DELETE FROM TB_COMN_CD WHERE COMN_CD = 'REG_CLAS_CD';
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'REG_CLAS_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'REG_CLAS_CD', 'ADM_PRPT', NULL, NULL, '등록종류코드', '관리자-매물등록', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'REG_CLAS_CD', 'ADM_SUGGST', NULL, NULL, '등록종류코드', '관리자-추천분양등록', NULL, 1.10, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'REG_CLAS_CD', 'ESTBRK_PRPT', NULL, NULL, '등록종류코드', '중개회원-매물등록', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'REG_CLAS_CD', 'ESTBRK_TRAN_PRPSL', NULL, NULL, '등록종류코드', '중개회원-기업이전제안서', NULL, 2.10, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'REG_CLAS_CD', 'ESTBRK_PRPSL', NULL, NULL, '등록종류코드', '중개회원-매물제안서', NULL, 2.20, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'REG_CLAS_CD', 'MY_PRPT', NULL, NULL, '등록종류코드', '일반회원-매물등록', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'REG_CLAS_CD', 'MY_ASST', NULL, NULL, '등록종류코드', '일반회원-자산등록', NULL, 3.10, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'REG_CLAS_CD', 'MY_PRPSL', NULL, NULL, '등록종류코드', '일반회원-매물제안서', NULL, 3.20, NOW(), 'N' );

-- 거래상태구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'DEAL_STAT_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'DEAL_STAT_GB_CD', 'ING', NULL, NULL, '거래상태구분코드', '거래중', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'DEAL_STAT_GB_CD', 'FIN', NULL, NULL, '거래상태구분코드', '거래완료', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'DEAL_STAT_GB_CD', 'PRV', NULL, NULL, '거래상태구분코드', '비공개', NULL, 3.00, NOW(), 'N' );

-- 활동상태구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'ACTV_STAT_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'ACTV_STAT_GB_CD', 'NOR', NULL, NULL, '거래상태구분코드', '활동가능', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ACTV_STAT_GB_CD', 'BLK', NULL, NULL, '거래상태구분코드', '활동중지', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ACTV_STAT_GB_CD', 'WDR', NULL, NULL, '거래상태구분코드', '탈퇴처리', NULL, 3.00, NOW(), 'N' );

-- 커뮤니티머리말코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'COMU_PREF_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'COMU_PREF_CD', 'F', NULL, NULL, '커뮤니티머리말코드', '자유글',  NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMU_PREF_CD', 'A', NULL, NULL, '커뮤니티머리말코드', '질문/답변', NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMU_PREF_CD', 'R', NULL, NULL, '커뮤니티머리말코드', '후기', NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMU_PREF_CD', 'K', NULL, NULL, '커뮤니티머리말코드', '노하우', NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMU_PREF_CD', 'Y', NULL, NULL, '커뮤니티머리말코드', '공톡유튜브', NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMU_PREF_CD', 'M', NULL, NULL, '커뮤니티머리말코드', '공톡매거진', NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMU_PREF_CD', 'K', NULL, NULL, '커뮤니티머리말코드', '공톡뉴스', NULL, 7.00, NOW(), 'N' );

-- 커뮤니티타입코드
INSERT INTO TB_COMN_CD VALUES ( 'COMU_TYPE_CD', 'C', NULL, NULL, '커뮤니티타입코드', '일반', NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMU_TYPE_CD', 'G', NULL, NULL, '커뮤니티타입코드', '공톡', NULL, 2.00, NOW(), 'N' );

-- 제안요청매물구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'SUGGST_ESTATE_TYP_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_ESTATE_TYP_CD', 'STR', NULL, NULL, '제안요청매물구분코드', '상가',  NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_ESTATE_TYP_CD', 'KOG', NULL, NULL, '제안요청매물구분코드', '지산/사무실/창고',  NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_ESTATE_TYP_CD', 'FTR', NULL, NULL, '제안요청매물구분코드', '단독공장',  NULL, 3.00, NOW(), 'N' );

-- 제안요청거래유형구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'SUGGST_TRAN_TYP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_TRAN_TYP_GB_CD', 'TRADE', NULL, NULL, '제안요청거래유형구분코드', '매매',  NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_TRAN_TYP_GB_CD', 'LEASE', NULL, NULL, '제안요청거래유형구분코드', '임대',  NULL, 2.00, NOW(), 'N' );

-- 제안요청업종코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'SUGGST_SECTR_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '01', NULL, NULL, '제안요청업종코드', '농업, 임업 및 어업',  NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '02', NULL, NULL, '제안요청업종코드', '광업',  NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '03', NULL, NULL, '제안요청업종코드', '제조업',  NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '04', NULL, NULL, '제안요청업종코드', '전기, 가스, 증기 및 공기조절 공급업',  NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '05', NULL, NULL, '제안요청업종코드', '수도, 하수 및 폐기물 처리, 원료 재생업',  NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '06', NULL, NULL, '제안요청업종코드', '건설업',  NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '07', NULL, NULL, '제안요청업종코드', '도매 및 소매업',  NULL, 7.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '08', NULL, NULL, '제안요청업종코드', '운수 및 창고업',  NULL, 8.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '09', NULL, NULL, '제안요청업종코드', '숙박 및 음식점업',  NULL, 9.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '10', NULL, NULL, '제안요청업종코드', '정보통신업',  NULL, 10.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '11', NULL, NULL, '제안요청업종코드', '금융 및 보험업',  NULL, 11.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '12', NULL, NULL, '제안요청업종코드', '부동산업',  NULL, 12.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '13', NULL, NULL, '제안요청업종코드', '전문, 과학 및 기술 서비스업',  NULL, 13.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '14', NULL, NULL, '제안요청업종코드', '사업시설 관리, 사업 지원 및 임대 서비스업',  NULL, 14.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '15', NULL, NULL, '제안요청업종코드', '공공 행정, 국방 및 사회보장 행정',  NULL, 15.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '16', NULL, NULL, '제안요청업종코드', '교육 서비스업',  NULL, 16.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '17', NULL, NULL, '제안요청업종코드', '보건업 및 사회복지 서비스업',  NULL, 17.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '18', NULL, NULL, '제안요청업종코드', '예술, 스포츠 및 여가관련 서비스업',  NULL, 18.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '19', NULL, NULL, '제안요청업종코드', '협회 및 단체, 수리 및 기타 개인 서비스업',  NULL, 19.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '20', NULL, NULL, '제안요청업종코드', '가구 내 고용활동 및 미분류 자가 소비생산업',  NULL, 20.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'SUGGST_SECTR_CD', '21', NULL, NULL, '제안요청업종코드', '국제 및 외국기관',  NULL, 21.00, NOW(), 'N' );

-- 희망층수유형코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'WISH_FLR_TYP_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'WISH_FLR_TYP_CD', '00', NULL, NULL, '희망층수유형코드', '상관없음',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'WISH_FLR_TYP_CD', '01', NULL, NULL, '희망층수유형코드', '1층', 	NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'WISH_FLR_TYP_CD', '02', NULL, NULL, '희망층수유형코드', '2층이상', 	NULL, 3.00, NOW(), 'N' );

-- 기업이전제안용매물유형구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'COMP_PRPSL_ESTATE_TYP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'COMMERCIAL', NULL, NULL, '기업이전제안용매물유형구분코드', '상업용',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'REGIDENTAL', NULL, NULL, '기업이전제안용매물유형구분코드', '주거용',	NULL, 2.00, NOW(), 'N' );

-- 기업이전제안용 매물구분코드 - 상업용
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'COMP_PRPSL_ESTATE_TYP_CD' AND UP_COMN_CD = 'COMP_PRPSL_ESTATE_TYP_GB_CD' AND UP_ITEM_CD = 'COMMERCIAL' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_CD', 'KWC', 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'COMMERCIAL', '기업이전제안용 매물구분코드', '지식산업센터',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_CD', 'STR', 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'COMMERCIAL', '기업이전제안용 매물구분코드', '상가',	NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_CD', 'OFC', 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'COMMERCIAL', '기업이전제안용 매물구분코드', '사무실',	NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_CD', 'BLD', 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'COMMERCIAL', '기업이전제안용 매물구분코드', '건물',	NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_CD', 'FCG', 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'COMMERCIAL', '기업이전제안용 매물구분코드', '공장/창고',	NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_CD', 'LND', 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'COMMERCIAL', '기업이전제안용 매물구분코드', '토지/임야',	NULL, 6.00, NOW(), 'N' );

-- 기업이전제안용 매물구분코드 - 주거용
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'COMP_PRPSL_ESTATE_TYP_CD' AND UP_COMN_CD = 'COMP_PRPSL_ESTATE_TYP_GB_CD' AND UP_ITEM_CD = 'REGIDENTAL' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_CD', 'APT', 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'REGIDENTAL', '기업이전제안용 매물구분코드', '아파트',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_CD', 'OFT', 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'REGIDENTAL', '기업이전제안용 매물구분코드', '오피스텔',	NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_CD', 'SHC', 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'REGIDENTAL', '기업이전제안용 매물구분코드', '상가주택',	NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_CD', 'HUS', 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'REGIDENTAL', '기업이전제안용 매물구분코드', '주택',	NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_CD', 'SMH', 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'REGIDENTAL', '기업이전제안용 매물구분코드', '단독/다가구',	NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_ESTATE_TYP_CD', 'TWN', 'COMP_PRPSL_ESTATE_TYP_GB_CD', 'REGIDENTAL', '기업이전제안용 매물구분코드', '다세대/빌라/연립',	NULL, 6.00, NOW(), 'N' );

-- 기업이전제안용거래유형구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'COMP_PRPSL_TRAN_TYP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_TRAN_TYP_GB_CD', 'TRADE', NULL, NULL, '기업이전제안용거래유형구분코드', '매매',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_TRAN_TYP_GB_CD', 'CHARTER', NULL, NULL, '기업이전제안용거래유형구분코드', '전세',	NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_TRAN_TYP_GB_CD', 'MONTLY', NULL, NULL, '기업이전제안용거래유형구분코드', '월세',	NULL, 3.00, NOW(), 'N' );

-- 기업이전제안건물시설유형코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'COMP_PRPSL_BLD_FAC_TYP_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_BLD_FAC_TYP_CD', 'DRVIN', NULL, NULL, '기업이전제안건물시설유형코드', '드라이브인',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_BLD_FAC_TYP_CD', 'OFFCL', NULL, NULL, '기업이전제안건물시설유형코드', '업무용',	NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_BLD_FAC_TYP_CD', 'INTRR', NULL, NULL, '기업이전제안건물시설유형코드', '인테리어',	NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_BLD_FAC_TYP_CD', 'TERRC', NULL, NULL, '기업이전제안건물시설유형코드', '테라스',	NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_BLD_FAC_TYP_CD', 'VRNDA', NULL, NULL, '기업이전제안건물시설유형코드', '베란다',	NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_BLD_FAC_TYP_CD', 'FRELV', NULL, NULL, '기업이전제안건물시설유형코드', '화물용승강기',	NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_BLD_FAC_TYP_CD', 'LDDOC', NULL, NULL, '기업이전제안건물시설유형코드', '하역장',	NULL, 7.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_BLD_FAC_TYP_CD', 'TOILT', NULL, NULL, '기업이전제안건물시설유형코드', '화장실',	NULL, 8.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_BLD_FAC_TYP_CD', 'SHWRM', NULL, NULL, '기업이전제안건물시설유형코드', '샤워장',	NULL, 9.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_BLD_FAC_TYP_CD', 'WDSNK', NULL, NULL, '기업이전제안건물시설유형코드', '싱크대',	NULL, 10.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_BLD_FAC_TYP_CD', 'RFRTR', NULL, NULL, '기업이전제안건물시설유형코드', '냉장고',	NULL, 11.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'COMP_PRPSL_BLD_FAC_TYP_CD', 'CLCLN', NULL, NULL, '기업이전제안건물시설유형코드', '세탁기',	NULL, 12.00, NOW(), 'N' );

-- 알림구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'NOTI_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'NOTI_GB_CD', 'PRPT',	NULL, NULL, '알림구분코드', '매물알림',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'NOTI_GB_CD', 'SALES',	NULL, NULL, '알림구분코드', '분양알림',	NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'NOTI_GB_CD', 'SCHDL',	NULL, NULL, '알림구분코드', '일정알림',	NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'NOTI_GB_CD', 'NOTI',	NULL, NULL, '알림구분코드', '공지알림',	NULL, 4.00, NOW(), 'N' );

-- 공지알림유형구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'NOTI_TYP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'NOTI_TYP_GB_CD', 'E',	NULL, NULL, '공지알림유형구분코드', '이벤트안내',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'NOTI_TYP_GB_CD', 'U',	NULL, NULL, '공지알림유형구분코드', '업데이트안내',	NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'NOTI_TYP_GB_CD', 'S',	NULL, NULL, '공지알림유형구분코드', '서비스안내',	NULL, 3.00, NOW(), 'N' );

-- 자산용거래유형구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'ASSET_TRAN_TYP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'ASSET_TRAN_TYP_GB_CD', 'TRADE',	NULL, NULL, '자산용거래유형구분코드', '매매',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ASSET_TRAN_TYP_GB_CD', 'PRESALE',	NULL, NULL, '자산용거래유형구분코드', '분양권',	NULL, 2.00, NOW(), 'N' );

-- 명의구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'INSP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'INSP_GB_CD', 'S',	NULL, NULL, '명의구분코드', '단독명의',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'INSP_GB_CD', 'M',	NULL, NULL, '명의구분코드', '공동명의',	NULL, 2.00, NOW(), 'N' );

-- 사업자구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'BIZMAN_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'BIZMAN_GB_CD', 'PB',	NULL, NULL, '사업자구분코드', '개인사업자',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BIZMAN_GB_CD', 'B',	NULL, NULL, '사업자구분코드', '법인사업자',	NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'BIZMAN_GB_CD', 'P',	NULL, NULL, '사업자구분코드', '개인',			NULL, 3.00, NOW(), 'N' );

-- 대출방식구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'LOAN_MTHD_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'LOAN_MTHD_GB_CD', '10',	NULL, NULL, '대출방식구분코드', '원리금균등분할',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LOAN_MTHD_GB_CD', '20',	NULL, NULL, '대출방식구분코드', '원리금균등상환',	NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'LOAN_MTHD_GB_CD', '90',	NULL, NULL, '대출방식구분코드', '만기상환',		NULL, 3.00, NOW(), 'N' );

-- 공실유형구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'EMPTY_TYP_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'EMPTY_TYP_GB_CD', 'E',	NULL, NULL, '공실유형구분코드', '공실',			NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'EMPTY_TYP_GB_CD', 'C',	NULL, NULL, '공실유형구분코드', '계약중',			NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'EMPTY_TYP_GB_CD', 'N',	NULL, NULL, '공실유형구분코드', '미임대',			NULL, 3.00, NOW(), 'N' );

-- 임대료납부방법구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'RENT_AMT_PAY_MTHD_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'RENT_AMT_PAY_MTHD_GB_CD', 'A',	NULL, NULL, '임대료납부방법구분코드', '후불',	NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'RENT_AMT_PAY_MTHD_GB_CD', 'F',	NULL, NULL, '임대료납부방법구분코드', '선불',	NULL, 2.00, NOW(), 'N' );

-- 월세입금일자구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'MONTHLY_PAY_DAY_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '01',	NULL, NULL, '월세입금일자구분코드', '1일',		NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '02',	NULL, NULL, '월세입금일자구분코드', '2일',		NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '03',	NULL, NULL, '월세입금일자구분코드', '3일',		NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '04',	NULL, NULL, '월세입금일자구분코드', '4일',		NULL, 4.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '05',	NULL, NULL, '월세입금일자구분코드', '5일',		NULL, 5.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '06',	NULL, NULL, '월세입금일자구분코드', '6일',		NULL, 6.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '07',	NULL, NULL, '월세입금일자구분코드', '7일',		NULL, 7.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '08',	NULL, NULL, '월세입금일자구분코드', '8일',		NULL, 8.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '09',	NULL, NULL, '월세입금일자구분코드', '9일',		NULL, 9.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '10',	NULL, NULL, '월세입금일자구분코드', '10일',	NULL, 10.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '11',	NULL, NULL, '월세입금일자구분코드', '11일',	NULL, 11.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '12',	NULL, NULL, '월세입금일자구분코드', '12일',	NULL, 12.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '13',	NULL, NULL, '월세입금일자구분코드', '13일',	NULL, 13.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '14',	NULL, NULL, '월세입금일자구분코드', '14일',	NULL, 14.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '15',	NULL, NULL, '월세입금일자구분코드', '15일',	NULL, 15.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '16',	NULL, NULL, '월세입금일자구분코드', '16일',	NULL, 16.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '17',	NULL, NULL, '월세입금일자구분코드', '17일',	NULL, 17.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '18',	NULL, NULL, '월세입금일자구분코드', '18일',	NULL, 18.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '19',	NULL, NULL, '월세입금일자구분코드', '19일',	NULL, 19.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '20',	NULL, NULL, '월세입금일자구분코드', '20일',	NULL, 20.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '21',	NULL, NULL, '월세입금일자구분코드', '21일',	NULL, 21.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '22',	NULL, NULL, '월세입금일자구분코드', '22일',	NULL, 22.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '23',	NULL, NULL, '월세입금일자구분코드', '23일',	NULL, 23.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '24',	NULL, NULL, '월세입금일자구분코드', '24일',	NULL, 24.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '25',	NULL, NULL, '월세입금일자구분코드', '25일',	NULL, 25.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '26',	NULL, NULL, '월세입금일자구분코드', '26일',	NULL, 26.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '27',	NULL, NULL, '월세입금일자구분코드', '27일',	NULL, 27.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '28',	NULL, NULL, '월세입금일자구분코드', '28일',	NULL, 28.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '29',	NULL, NULL, '월세입금일자구분코드', '29일',	NULL, 29.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '30',	NULL, NULL, '월세입금일자구분코드', '30일',	NULL, 30.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'MONTHLY_PAY_DAY_GB_CD', '99',	NULL, NULL, '월세입금일자구분코드', '말일',	NULL, 99.00, NOW(), 'N' );

-- 계정승인상태코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'ACNT_APRV_STAT_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'ACNT_APRV_STAT_CD', 'Y',	NULL, NULL, '계정승인상태코드', '승인',			NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ACNT_APRV_STAT_CD', 'N',	NULL, NULL, '계정승인상태코드', '미승인',			NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ACNT_APRV_STAT_CD', 'D',	NULL, NULL, '계정승인상태코드', '거부',			NULL, 3.00, NOW(), 'N' );

-- 자산첨부서류구분코드
SELECT * FROM TB_COMN_CD WHERE COMN_CD = 'ASSET_ATT_DOC_GB_CD' ORDER BY SORT_SERL;
INSERT INTO TB_COMN_CD VALUES ( 'ASSET_ATT_DOC_GB_CD', 'SC',	NULL, NULL, '자산첨부서류구분코드', '매매계약서',		NULL, 1.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ASSET_ATT_DOC_GB_CD', 'BR',	NULL, NULL, '자산첨부서류구분코드', '사업자등록증',		NULL, 2.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ASSET_ATT_DOC_GB_CD', 'RC',	NULL, NULL, '자산첨부서류구분코드', '임대차계약',		NULL, 3.00, NOW(), 'N' );
INSERT INTO TB_COMN_CD VALUES ( 'ASSET_ATT_DOC_GB_CD', 'ET',	NULL, NULL, '자산첨부서류구분코드', '기타서류',			NULL, 4.00, NOW(), 'N' );